// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orkglysbmxdrbxulkplj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ya2dseXNibXhkcmJ4dWxrcGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTgyODEsImV4cCI6MjA2MzgzNDI4MX0.Ot0LkqXwBnsU9pV-je7mL3TRcBy3JMn5XnhLSooZqC4";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this: